### PR TITLE
Implement text search on card ability

### PR DESCRIPTION
**Pull request by KittySparkles**

### CODE REVIEW

**Comment by KittySparkles** [comment]
@MaxMihawk If you want to have a look. :)

**Comment by KittySparkles** [comment]
@MaxMihawk It’s live!

**Comment by MaxMihawk** [comment]
Oh man, that´s great. I´m missing wildcards xD . "deal * damage" or "deal damage" gives 0 results.

**Comment by KittySparkles** [comment]
@MaxMihawk I just implemented wildcards with https://github.com/KittySparkles/stormbound-kitty/commit/1059b94d7c2a7991f6700f6074f72e7c3a0c7fbd. Let me know if that solves your needs. 😊

**Comment by MaxMihawk** [comment]
Oh man, that´s rly great :) . This deserves a more prominent frontpage link. Thx

**Pull request merged**
